std = "lua51"
max_line_length = false
unused_args = false

globals = {
    "XalsAutoMacDB",
    "XalsAutoMacFrame",
    "SLASH_XALSAUTOMAC1",
    "SLASH_XALSAUTOMAC2",
    "SlashCmdList",
    "StaticPopupDialogs", -- a real mutable table addons add popup entries to
}

read_globals = {
    "UnitName",
    "GetRealmName",
    "UnitClass",
    "UnitLevel",
    "Item",
    "GetItemInfo",
    "GetMacroIndexByName",
    "EditMacro",
    "CreateMacro",
    "CreateFrame",
    "UIParent",
    "GameFontHighlight",
    "GameFontNormal",
    "GameFontNormalSmall",
    "UIErrorsFrame",
    "PixelUtil",
    "C_AddOns",
    "C_Spell",
    "C_SpellBook",
    "C_Timer",
    "Enum",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GameTooltip",
    "GetMacroInfo",
    "ShowMacroFrame",
    "MacroFrame",
    "MacroFrameText",
    "MacroSaveButton",
    "MacroCancelButton",
    "MacroDeleteButton",
    "MacroNewButton",
    "MacroExitButton",
    "MacroEditButton",
    "MacroFrameTab1",
    "MacroFrameTab2",
    "MacroHorizontalBarLeft",
    "MacroFrameSelectedMacroBackground",
    "MacroFrameTextBackground",
    "MacroFrameCharLimitText",
    "PanelTemplates_SetTab",
    "Constants",
    "hooksecurefunc",
    "LibStub",
    "tinsert",
    "UISpecialFrames",
    "GameFontHighlightSmall",
    "RaidWarningFrame",
    "Settings",
    "InterfaceOptions_AddCategory",
    "StaticPopup_Show",
    "MacroPopupFrame",
}
